In [13]:
import numpy as np

In [16]:
def pad_ours(p,A):
  C = np.zeros((A.shape[0],A.shape[1]+2*p,A.shape[2]+2*p,A.shape[3]))
  C[:,p:p+A.shape[1],p:p+A.shape[2],:] = A
  return C

def pad(p,A):
  return np.pad(A,((0,0),(p,p),(p,p),(0,0)))


In [15]:
A = np.array([[[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]],[[[-1,-2,-3],[-4,-5,-6]],[[100,200,300],[400,500,600]]]])
p = 1
B = pad(p,A)
np.pad(A,((0,0),(p,p),(p,p),(0,0))) == B

array([[[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True, 

In [11]:
A.shape
print(B.shape)
print(np.pad(A,((0,0),(p,p),(p,p),(0,0))).shape)

(2, 4, 4, 3)
(2, 4, 4, 3)


In [ ]:
print(A[:,:,2])
print(B[:,:,2])

[[ 3  6]
 [30 60]]
[[ 0.  0.  0.  0.]
 [ 0.  3.  6.  0.]
 [ 0. 30. 60.  0.]
 [ 0.  0.  0.  0.]]


In [ ]:
A.shape

(2, 2, 3)

In [ ]:
B.shape

(4, 4, 3)

In [3]:
a = [1, 2, 3, 4, 5]
np.pad(a, ((2, 3), 'constant', constant_values=(0, 0))

array([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])

In [4]:
A = np.array([[[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]],[[[-1,-2,-3],[-4,-5,-6]],[[100,200,300],[400,500,600]]]])
p = 1
np.pad(A,((0,0),(p,p),(p,p),(0,0)))

array([[[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  1,   2,   3],
         [  4,   5,   6],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [ 10,  20,  30],
         [ 40,  50,  60],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]]],


       [[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [ -1,  -2,  -3],
         [ -4,  -5,  -6],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [100, 200, 300],
         [400, 500, 600],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]]]])