In [1]:
import numpy as np

array of all ones

In [2]:
def add_one_end_rows(X):
  return np.column_stack((X, np.ones(X.shape[0])))

def best_lin(X,y):
  C = add_one_end_rows(X)
  A = np.matmul(C.T,C)
  print(A)
  r = np.dot(C.T,y)
  print(r)
  z = np.linalg.solve(A,r)
  w = z[:-1]
  b = z[-1]
  return w, b

Importing pandas

In [3]:
import pandas as pd

mounting the drive

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


reading the csv file into the dataframe df

In [6]:
df = pd.read_csv('/content/drive/MyDrive/Data/houses.csv')

looking at the first 5 rows of df

In [7]:
df.head()

Square feet  Bedrooms   Price
0         2104         3  399900
1         1600         3  329900
2         2400         3  369000
3         1416         2  232000
4         3000         4  539900

In [8]:
a = df[:5]

In [9]:
a

Square feet  Bedrooms   Price
0         2104         3  399900
1         1600         3  329900
2         2400         3  369000
3         1416         2  232000
4         3000         4  539900

In [10]:
d={'':['Mean','Standar deviation'],'Square feet':[2104,636],'Bedrooms':['3','0.71'],'Price':[374140,112168]}
pd.DataFrame(d) 


Square feet Bedrooms   Price
0               Mean         2104        3  374140
1  Standar deviation          636     0.71  112168

In [12]:
b = (a-a.mean())/a.std()
b.rename(columns = {'Square feet':'Scaled square feet', 'Bedrooms':'Scaled bedrooms', 'Price':'Scaled price = y'}, inplace = True)
b

Scaled square feet  Scaled bedrooms  Scaled price = y
0            0.000000         0.000000          0.229654
1           -0.792500         0.000000         -0.394406
2            0.465436         0.000000         -0.045824
3           -1.081825        -1.414214         -1.267198
4            1.408889         1.414214          1.477773

In [13]:
b['Predicted scaled price = y'] = 0.2+0.8*b['Scaled price = y']
b

Scaled square feet  ...  Predicted scaled price = y
0            0.000000  ...                    0.383723
1           -0.792500  ...                   -0.115525
2            0.465436  ...                    0.163341
3           -1.081825  ...                   -0.813758
4            1.408889  ...                    1.382219

[5 rows x 4 columns]

In [14]:
b['(y-y) ']= (b['Predicted scaled price = y']-b['Scaled price = y'])**2
b

Scaled square feet  Scaled bedrooms  ...  Predicted scaled price = y    (y-y) 
0            0.000000         0.000000  ...                    0.383723  0.023737
1           -0.792500         0.000000  ...                   -0.115525  0.077775
2            0.465436         0.000000  ...                    0.163341  0.043750
3           -1.081825        -1.414214  ...                   -0.813758  0.205607
4            1.408889         1.414214  ...                    1.382219  0.009131

[5 rows x 5 columns]

In [18]:
c = b['(y-y) '].sum()/5
print(c*374140)

26938.079999999998


In [24]:
d={'Scaled square feet':['(2104-2104)/636','(1600-2104)/636','(2400-2104)/636','(1416-2104)/636','(3000-2104)/636'],'Scaled bedrooms':['(3-3)/0.71','(3-3)/0.71','(3-3)/0.71','(2-3)/0.71','(4-3)/0.71']} 
df = pd.DataFrame(data=d)
df

Scaled square feet Scaled bedrooms
0    (2104-2104)/636      (3-3)/0.71
1    (1600-2104)/636      (3-3)/0.71
2    (2400-2104)/636      (3-3)/0.71
3    (1416-2104)/636      (2-3)/0.71
4    (3000-2104)/636      (4-3)/0.71

In [15]:
a.sum()

Square feet      10520
Bedrooms            15
Price          1870700
dtype: int64

In [16]:
10520/5

2104.0

create the matrix of features $X$ and the vector of labels $y$

In [ ]:
y = df['Price'].values

In [ ]:
X = df[['Square feet','Bedrooms']].values

In [ ]:
w,b = best_lin(X,y)
print(w,b)

[[2.17179406e+08 3.13679000e+05 9.40320000e+04]
 [3.13679000e+05 4.99000000e+02 1.49000000e+02]
 [9.40320000e+04 1.49000000e+02 4.70000000e+01]]
[3.5917829e+10 5.2657282e+07 1.5999395e+07]
[  139.21067402 -8738.01911233] 89597.90954279735


Predict the value of a house 3000 sq feet 4 bedrooms

In [ ]:
X

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4],
       [1985,    4],
       [1534,    3],
       [1427,    3],
       [1380,    3],
       [1494,    3],
       [1940,    4],
       [2000,    3],
       [1890,    3],
       [4478,    5],
       [1268,    3],
       [2300,    4],
       [1320,    2],
       [1236,    3],
       [2609,    4],
       [3031,    4],
       [1767,    3],
       [1888,    2],
       [1604,    3],
       [1962,    4],
       [3890,    3],
       [1100,    3],
       [1458,    3],
       [2526,    3],
       [2200,    3],
       [2637,    3],
       [1839,    2],
       [1000,    1],
       [2040,    4],
       [3137,    3],
       [1811,    4],
       [1437,    3],
       [1239,    3],
       [2132,    4],
       [4215,    4],
       [2162,    4],
       [1664,    2],
       [2238,    3],
       [2567,    4],
       [1200,    3],
       [ 852,    2],
       [1852,    4],
       [1203,    3]])

In [ ]:
def predictions(x,w,b):
  return np.dot(x,w)+b

y_hat = predictions(X,w,b)  