In [ ]:
import numpy as np

In [ ]:
A = np.array([[3,-2,1], [1,0,-2], [0,-1,3]])
b = np.array([1,0,1])

In [ ]:
print(A)

[[ 3 -2  1]
 [ 1  0 -2]
 [ 0 -1  3]]


In [ ]:
print(b)

[1 0 1]


In [ ]:
z = np.linalg.solve(A,b)
print(z)

[-2. -4. -1.]
