In [ ]:
import numpy as np

Matrices as numpy arrays

In [ ]:
A = np.array([[-1,0,2],[5,-3,0]])
print(A)

[[-1  0  2]
 [ 5 -3  0]]


$A[i]$ gives the $(i+1)^{th}$ row

In [ ]:
A[0] #this is the first row

array([-1,  0,  2])

Two ways to the components of matrices

In [ ]:
print(A[0][2])
print(A[0,2])

2
2


In [ ]:
print(A)
x = 3
print(x*A)

[[-1  0  2]
 [ 5 -3  0]]
[[-3  0  6]
 [15 -9  0]]


In [ ]:
A = np.array([[-1,0,2],[5,-3,0]])
B = np.array([[1,10,12],[7,-1,2]])
print(A)
print(B)
print(A+B)

[[-1  0  2]
 [ 5 -3  0]]
[[ 1 10 12]
 [ 7 -1  2]]
[[ 0 10 14]
 [12 -4  2]]


Matrix-matrix multiplication

In [ ]:
A = np.array([[2,-1],[0,1]])
B = np.array([[-1,1,2],[1,0,3]])
np.matmul(A,B)

array([[-3,  2,  1],
       [ 1,  0,  3]])

In [ ]:
b = np.array([1,4,2])

Function shape

In [ ]:
A.shape

(2, 2)

In [ ]:
print(B.shape)
print('number of rows =', B.shape[0])
print('number of columns =', B.shape[1])
print(B)

(2, 3)
number of rows = 2
number of columns = 3
[[-1  1  2]
 [ 1  0  3]]


In [ ]:
print(b.shape)
print('number of elements =', b.shape[0])
print(b)

(3,)
number of elements = 3
[1 4 2]


Transpose of a matrix

In [ ]:
print('B =', B)
print('the transpose of B =')
print(B.T)

B = [[-1  1  2]
 [ 1  0  3]]
the transpose of B =
[[-1  1]
 [ 1  0]
 [ 2  3]]
