In [1]:
import numpy as np

In [2]:
A = np.array([[1,-1,2],[0,3,-2]])
x = np.array([0,1,3])

In [3]:
np.dot(A,x)

array([ 5, -3])

In [4]:
np.matmul(A,x)

array([ 5, -3])

In [7]:
A = np.array([[0,-1,3],[1,0,1]])
x = np.array([2,1])
print(np.dot(x,A))
print(np.matmul(x,A))

[ 1 -2  7]
[ 1 -2  7]


In [8]:
A = np.array([[3,0,-2],[1,2,0],[3,-1,1]])
b = np.array([1,0,2])
z = np.linalg.solve(A,b)
print(z)

[ 0.5  -0.25  0.25]


In [9]:
np.matmul(A,z)

array([1., 0., 2.])

Dot product of vectors

In [10]:
x = np.array([1,0,-2])
y = np.array([3,5,2])
np.dot(x,y)

-1

In [11]:
np.matmul(x,y)

-1