In [ ]:
import numpy as np

In [ ]:
def row_pool(f,s,sec_A):
  ncA = sec_A.shape[1]
  row = np.array([])
  j = 0
  while j+f <= ncA:
    row = np.append(row,np.max(sec_A[:,j:j+f]))
    j = j+s
  return row  

def pool_2d(f,s,A):
  i = 0
  nrA = A.shape[0]
  C = row_pool(f,s,A[0:0+f,:]).reshape((1,-1))
  i = i+s
  while i + f <= nrA:
    C = np.append(C,row_pool(f,s,A[i:i+f,:]).reshape((1,-1)), axis = 0)
    i = i+s
  return C  

def pool_one_ex(f,s,A):
  B = pool_2d(f,s,A[:,:,0])
  C = B.reshape((B.shape[0],B.shape[1],1))
  for i in range(1,A.shape[2]):
    B = pool_2d(f,s,A[:,:,i])
    B = B.reshape((B.shape[0],B.shape[1],1))
    C = np.append(C,B, axis = 2)
  return C 

def pool(f,s,A):
  B = pool_one_ex(f,s,A[0,:,:,:])
  C = B.reshape((1,B.shape[0],B.shape[1],B.shape[2]))
  for i in range(1,A.shape[0]):
    B = pool_one_ex(f,s,A[i,:,:,:])
    B = B.reshape((1,B.shape[0],B.shape[1],B.shape[2]))
    C = np.append(C,B, axis = 0)
  return C  

In [ ]:
A1 = np.array([[1,2,-1,1,8],[3,5,0,2,-1],[1,7,5,0,3],[2,1,-1,7,2],[3,4,2,5,-1]])
f = 3
s = 2
pool_2d(f,s,A1)

array([[7., 8.],
       [7., 7.]])

In [ ]:
A2 = np.array([[10,12,-1,5,8],[13,5,0,4,-1],[1,7,5,0,3],[2,1,-1,27,2],[3,4,2,5,-1]])
f = 3
s = 2
pool_2d(f,s,A2)

array([[13.,  8.],
       [ 7., 27.]])

In [ ]:
C1 = A1.reshape((A1.shape[0],A1.shape[1],1))
C2 = A2.reshape((A2.shape[0],A2.shape[1],1))
C = np.append(C1,C2,axis=2)

In [ ]:
print(C[:,:,1])
A2

[[10 12 -1  5  8]
 [13  5  0  4 -1]
 [ 1  7  5  0  3]
 [ 2  1 -1 27  2]
 [ 3  4  2  5 -1]]


array([[10, 12, -1,  5,  8],
       [13,  5,  0,  4, -1],
       [ 1,  7,  5,  0,  3],
       [ 2,  1, -1, 27,  2],
       [ 3,  4,  2,  5, -1]])

In [ ]:
C_pool = pool(f,s,C)
A1_pool = pool_2d(f,s,A1)
A2_pool = pool_2d(f,s,A2)

In [ ]:
C_pool[:,:,1]

array([[13.,  8.],
       [ 7., 27.]])

In [ ]:
A2_pool

array([[13.,  8.],
       [ 7., 27.]])