In [7]:
import numpy as np

In [10]:
def row_conv_2d(W,s,sec_A):
  f = W.shape[1]
  ncA = sec_A.shape[1]
  row = np.array([])
  j = 0
  while j+f <= ncA:
    row = np.append(row,np.sum(sec_A[:,j:j+f]*W))
    j = j+s
  return row  

def conv_2d_2d(W,s,A):
# nrW - number of rows in W
  f = W.shape[0]
# nrA = number of rows in A  
  nrA = A.shape[0]
  i = 0
  sec_A = A[i:i+f,:]
  row = row_conv_2d(W,s,sec_A)
# B is the convolution, we add one row at the time
  B = row.reshape((1,-1))
  i = i+s   
  while i+f <= nrA:
    sec_A = A[i:i+f,:]
    row = row_conv_2d(W,s,sec_A)
    row = row.reshape((1,-1))
# add row as a new row in B at the end
    B = np.append(B, row, axis = 0)    
    i = i+s
  return B

def row_conv_3d(W,s,sec_A):
  f = W.shape[1]
  ncA = sec_A.shape[1]
  row = np.array([])
  j = 0
  while j+f <= ncA:
    row = np.append(row,np.sum(sec_A[:,j:j+f,:]*W))
    j = j+s
  return row  
  
def conv_3d_3d(W,s,A):
# nrW - number of rows in W
  f = W.shape[0]
# nrA = number of rows in A  
  nrA = A.shape[0]
  i = 0
  sec_A = A[i:i+f,:,:]
  row = row_conv_3d(W,s,sec_A)
# B is the convolution, we add one row at the time
  B = row.reshape((1,-1))
  i = i+s   
  while i+f <= nrA:
    sec_A = A[i:i+f,:,:]
    row = row_conv_3d(W,s,sec_A)
    row = row.reshape((1,-1))
# add row as a new row in B at the end
    B = np.append(B, row, axis = 0)    
    i = i+s
  return B  

def conv_4d_3d(W,s,A):
  n_filters = W.shape[3]
  filter = W[:,:,:,0]
  C = conv_3d_3d(filter,s,A)
  B = C.reshape((C.shape[0],C.shape[1],1))
  for i in range(1,n_fliters):
    filter = W[:,:,:,i]
    C = conv_3d_3d(filter,s,A)
    C = C.reshape((C.shape[0],C.shape[1],1))
    B = np.append(B, C, axis = 2)    
  return B    

def conv_4d_4d(W,s,A):
  n_ex = A.shape[0]
  A_ex = A[0,:,:,:]
  C = conv_4d_3d(W,s,A_ex)
  B = C.reshape((1,C.shape[0],C.shape[1],C.shape[2]))
  for i in range(1,n_ex):
    A_ex = A[i,:,:,:]
    C = conv_4d_3d(W,s,A_ex)
    C = C.reshape((1,C.shape[0],C.shape[1],C.shape[2]))
    B = np.append(B, C, axis = 0)    
  return B   

In [9]:
A = np.array([[2,0,-1,1,2,3],[0,1,-2,0,4,-1],[0,-1,3,1,2,0],[3,5,7,-1,2,5],[1,-2,0,1,3,5]])
W = np.array([[2,-1,3],[0,1,2]])
s = 2
print(A)
print(W)
print(conv_2d_2d(W,s,A))

[[ 2  0 -1  1  2  3]
 [ 0  1 -2  0  4 -1]
 [ 0 -1  3  1  2  0]
 [ 3  5  7 -1  2  5]
 [ 1 -2  0  1  3  5]]
[[ 2 -1  3]
 [ 0  1  2]]
[[-2. 11.]
 [29. 14.]]


In [ ]:
def row_conv(W,s,sec_A):
  f = W.shape[1]
  ncA = sec_A.shape[1]
  row = np.array([])
  j = 0
  while j+f <= ncA:
    row = np.append(row,np.sum(sec_A[:,j:j+f]*W))
    j = j+s
  return row  

def conv_old(W,s,A):
# nrW - number of rows in W
  f = W.shape[0]
# nrA = number of rows in A  
  nrA = A.shape[0]
  i = 0
  sec_A = A[i:i+f,:]
  row = row_conv(W,s,sec_A)
# B is the convolution, we add one row at the time
  B = row.reshape.((1,-1))
  i = i+s   
  while i+f <= nrA:
    sec_A = A[i:i+f,:]
    row = row_conv(W,s,sec_A)
    row = row.reshape.((1,-1))
# add row as a new row in B at the end
    B = np.append(B, row, axis = 0)    
    i = i+s
  return B





































def conv_old(W,s,A):
  i = 0
  nrW = W.shape[0]
  nrA = A.shape[0]
  C = row_conv(W,s,A[0:0+nrW,:,:]).reshape((1,-1))
  i = i+s
  while i+nrW <= nrA:
    C = np.append(C,row_conv(W,s,A[i:i+nrW,:,:]).reshape((1,-1)), axis = 0)
    i = i+s
  return C  

def conv_one_ex(W,s,A):
  B = conv_old(W[:,:,:,0],s,A)
  C = B.reshape((B.shape[0],B.shape[1],B.shape[2],1))
  for i in range(1,W.shape[3]):
    B = conv_old(W[:,:,:,i],s,A)
    B = B.reshape((B.shape[0],B.shape[1],B.shape[2],1))
    C = np.append(C,B, axis = 3)
  return C

def conv(W,s,A):
  B = conv_one_ex(W,s,A[0,:,:,:])
  C = B.reshape((1,B.shape[0],B.shape[1],B.shape[2],B.shape[3]))
  for i in range(1,A.shape[0]):
    B = conv_one_ex(W,s,A[i,:,:,:])
    B = B.reshape((1,B.shape[0],B.shape[1],B.shape[2],B.shape[3]))
    C = np.append(C,B, axis = 0)
  return C  

In [ ]:
A = np.array([[[2],[0],[-1],[1],[2],[3]],[[0],[1],[-2],[0],[4],[-1]],[[0],[-1],[3],[1],[2],[0]],[[3],[5],[7],[-1],[2],[5]],[[1],[-2],[0],[1],[3],[5]]])
W = np.array([[[2],[-1],[3]],[[0],[1],[2]]])
s = 2
conv(W,s,A)

array([[-2., 11.],
       [29., 14.]])

In [ ]:
A = np.append(np.array([1,2]).reshape(-1,1),np.array([3,4]).reshape(-1,1), axis = 1)

In [ ]:
A[:,1]

array([3, 4])

In [ ]:
A

array([[1, 3],
       [2, 4]])

In [ ]:
A.reshape((A.shape[0],1))

array([[1],
       [2]])

In [ ]:
range(1:3) 

SyntaxError: ignored

In [ ]:
X = np.empty((0, 2), float)
X.shape

(0, 2)

In [ ]:
X = np.append(X,np.array([[1,2]]),axis = 0)

In [ ]:
X

array([[1., 2.]])

In [ ]:
X = np.append(X,np.array([[3,4]]),axis = 0)

In [ ]:
X

array([[1., 2.],
       [3., 4.]])

In [ ]:
np.empty(0)

array([], dtype=float64)

In [ ]:
X = np.array([])

In [ ]:
X = np.append(X,4)

In [ ]:
X

array([4., 4.])